### ISSUE TITLE
What should interact do?

### ISSUE THREAD

**Issue by MrShroom1988** [rug-oop/2019_assignments#10]
In section 7.5 it tells us to implement interact in door. Do we need to replace our previous method of going through doors with this? Or do you mean something else?

Additionally, what is the use of interfaces? I don't see what they add. If every class that implements an interface has to define the methods in that interface anyway, what does the existence of the interface add?

**Comment by BugelNiels** [comment]
Interfaces can ben used if you want multiple classes to have the same capabilities.
If you have a lot of classes that you need to "interact" with, then you can use an interface for this.
The point of interfaces is not necessarily to always add additional functionality. Its main purpose is to improve clarity and consistency. If you have a lot of classes that can be interacted with, you will most likely have a lot of classes that implement the same method: _interact_. By implementing the interface you ensure that every interactable class HAS to implement this method. That way it is easy to see which classes you can interact with and which classes you cannot.

In the reader it says the you can use the interface _interactable_ for the method _interact_. This means that every class that implements the interface _interactable_ has to implement a method called _interact_.
Since you already implemented the method _interact_ for doors, you will not have to change this method. You only have to add the interface to the class.

I hope this clears things up. If you have more questions, do not hesitate to ask :p

**Comment by MrShroom1988** [comment]
Thanks for your reply, it's really helpful!
